the-gossip-project-app/config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "up" => "rails/health#show", as: :rails_health_check

  resources :welcome, only: [:show]
  resources :users, only: [:show, :new, :create]
  resources :teams, only: [:index]
  resources :contacts, only: [:new, :create]
  resources :gossips do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :likes, only: [:create, :destroy], controller: "comment_likes"
    end
  end
  resources :cities, only: [:show]
  resources :sessions, only: [:new, :create, :destroy]
end

the-gossip-project-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

the-gossip-project-app/app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips
end

the-gossip-project-app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable
end

the-gossip-project-app/app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :join_table_gossip_tags, dependent: :destroy
  has_many :tags, through: :join_table_gossip_tags, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3, maximum: 14 }
  validates :content, presence: true
end

the-gossip-project-app/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
  validates :user_id, uniqueness: { scope: [:likeable_type, :likeable_id] }
end

the-gossip-project-app/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :recipient, class_name: "User" #set sender&recipient as ALIAS of User
  belongs_to :sender, class_name: "User"
end

the-gossip-project-app/app/models/tag.rb
class Tag < ApplicationRecord
  before_create -> { self.color ||= [
  "#D62828", # rouge foncé
  "#F77F00", # orange
  "#FCBF49", # jaune foncé
  "#003049", # bleu marine
  "#264653", # vert foncé
  "#1B4965", # bleu
  "#5A0F3C", # violet foncé
  "#6A4C93", # violet
  "#2D6A4F", # vert
  "#343A40"  # gris foncé
  ].sample }
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

the-gossip-project-app/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage" #set sender&recipient as ALIAS of PrivateMessage
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  validates :password, presence: true, length: {minimum: 6}
  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update_attribute(:remember_digest, remember_digest)
  end
end

the-gossip-project-app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gossips = Gossip.all
    @first_name = current_user&.first_name
  end
end

the-gossip-project-app/app/helpers/application_helper.rb
module ApplicationHelper
end

the-gossip-project-app/app/helpers/cities_helper.rb
module CitiesHelper
end

the-gossip-project-app/app/helpers/comments_helper.rb
module CommentsHelper
end

the-gossip-project-app/app/helpers/contact_helper.rb
module ContactHelper
end

the-gossip-project-app/app/helpers/gossips_helper.rb
module GossipsHelper
end

the-gossip-project-app/app/helpers/home_helper.rb
module HomeHelper
end

the-gossip-project-app/app/helpers/likes_helper.rb
module LikesHelper
end

the-gossip-project-app/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      # S'il y a une session, on l'utilise (comportement classique)
      @current_user = User.find_by(id: session[:user_id])
      
    elsif cookies[:user_id]
      # S'il n'y a pas de session mais un cookie, on cherche l'utilisateur lié
      user = User.find_by(id: cookies[:user_id])
      
      # On vérifie que l'utilisateur existe ET que le token du cookie correspond au digest en BDD
      if user && user.remember_digest && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        session[:user_id] = user.id # On recrée la session temporaire pour naviguer plus vite ensuite
        @current_user = user
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    # On génère un token aléatoire (une suite de caractères au hasard)
    remember_token = SecureRandom.urlsafe_base64

    # On utilise la méthode de ton modèle User pour hasher et sauvegarder ce token en BDD
    user.remember(remember_token)

    # On stocke l'ID et le token en clair dans les cookies permanents (pour 20 ans !) du navigateur
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)
    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update_attribute(:remember_digest, nil)
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
    @current_user = nil
  end
end

the-gossip-project-app/app/helpers/team_helper.rb
module TeamHelper
end

the-gossip-project-app/app/helpers/users_helper.rb
module UsersHelper
end

the-gossip-project-app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

the-gossip-project-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "The Gossip Project App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  </head>
  <header>
    <%= render 'shared/navbar' %>
  </header>
  <body class="d-flex flex-column min-vh-100">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

the-gossip-project-app/app/views/shared/_footer.html.erb
<footer class="mt-auto bg-dark text-white py-3">
  <div class="container">
    
    <div class="row g-2">
      
      <div class="col-md-4">
        <h6 class="mb-1">À propos</h6>
        <p class="mb-0">Petite start-up qui gère de ouf dans le partage de ragots et de saloperies sur les gens</p>
      </div>
      <div class="col-md-4">
        <h6 class="mb-1">Liens rapides</h6>
        <ul class="list-unstyled mb-0">
          <li><%= link_to "Page d'accueil", root_path, class: "text-decoration-none text-white" %></li>
          <li><%= link_to "Team", teams_path, class: "text-decoration-none text-white" %></li>
          <li><%= link_to "Contact", new_contact_path, class: "text-decoration-none text-white" %></li>
        </ul>
      </div>

      <div class="col-md-4">
        <h6 class="mb-1">Nous suivre</h6>
        <ul class="list-inline mb-0">
          <li class="list-inline-item"><a href="#" class="text-white"><i class="bi bi-facebook"></i></a></li>
          <li class="list-inline-item"><a href="#" class="text-white"><i class="bi bi-twitter"></i></a></li>
          <li class="list-inline-item"><a href="#" class="text-white"><i class="bi bi-instagram"></i></a></li>
        </ul>
      </div>

    </div>

    <hr class="my-2">

    <div class="text-center">
      <p class="mb-0">&copy; 2026 The Gossip Project</p>
    </div>

  </div>
</footer>

the-gossip-project-app/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-2 fixed-top">
    <%= link_to image_tag("Gossip-icon.png", alt: "Logo", height: 40), root_path, class: "navbar-brand" %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse p-2" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <%= link_to "Accueil", root_path, class: "nav-link active", "aria-current"=>"page"%>
            </li>
            <li class="nav-item">
                <%= link_to "Notre équipe", teams_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to "Nous contacter", new_contact_path, class: "nav-link"%>
            </li>
            <!-- Condition for logout only if current_user connected -->
            <% if current_user %>
                <li class="nav-item">
                    <%= link_to "Deconnexion", session_path(session.id), data: { turbo_method: :delete }, class: "nav-link"%>
                </li>
                <li class="nav-item">
                    <span class="nav-link text">Connecté en tant que <%= current_user.first_name %></span>
                </li>
            <!-- Menu login/signin only if user is not connected -->    
            <% else %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    S'inscrire / Se connecter </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "S'inscrire", new_user_path, class: "dropdown-item" %></li>
                        <li><%= link_to "Se connecter", new_session_path, class: "dropdown-item" %></li>
                    </ul>
                </li>
            <% end %>
        </ul>
        <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Rechercher" aria-label="Search">
            <button class="btn btn-outline-light" type="submit">Rechercher</button>
        </form>
    </div>
</nav>